Added helper function for symlink cleanup
openshift/local-storage-operator pull request #254
Opened 2021-07-09 13:42 UTC by priyanka19-98

Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

2021-07-09 13:43 UTC, priyanka19-98 commented
@rohan47

2021-07-12 10:56 UTC, sp98 requested changes
Please add more details to the ticket description and commit message. Like why this change is needed in the first place, etc.

2021-07-12 10:56 UTC, sp98 commented on common/symlink_utils.go
> +		if err != nil {
this `err` is not returned.

2021-07-12 13:57 UTC, priyanka19-98 commented on common/symlink_utils.go
> +		if err != nil {
Thanks, made the change.

2021-12-09 16:11 UTC, closed without merging